CREATE TABLE [ref].[BuildPlanJobs]
(
[JobID] [int] NOT NULL,
[JobName] [nvarchar] (50) NULL,
[JobDescription] [nvarchar] (100) NULL,
[MinorModel] [nvarchar] (50) NULL,
[AirStair] [bit] NULL,
[CanTravel] [bit] NULL,
[ProfitCenter] [int] NULL,
[CostCenter] [nvarchar] (50) NULL,
[WC] [nvarchar] (50) NULL,
[WorkCenter] [nvarchar] (50) NULL,
[ACC] [int] NULL,
[FabAssemblyFlag] [nvarchar] (50) NOT NULL,
[AreaID] [nvarchar] (50) NULL,
[SubAreaID] [nvarchar] (50) NULL,
[Substation] [nvarchar] (255) NULL,
[Part_Family] [nvarchar] (50) NULL,
[ProcessType] [nvarchar] (50) NULL,
[Standards] [float] NULL,
[JobExpectedDurationInMin] [float] NOT NULL,
[LaborGrade] [nvarchar] (50) NULL,
[JobCode] [nvarchar] (50) NULL,
[SINumber] [nvarchar] (50) NULL,
[Operation_Fab] [int] NULL,
[MaterialNumber] [nvarchar] (50) NULL,
[MaterialDesc] [nvarchar] (50) NULL,
[NumberMechanics] [int] NOT NULL,
[CriticalPath] [nvarchar] (50) NULL,
[CreatedOn] [datetime2] NULL,
[CreatedBy] [nvarchar] (50) NULL,
[ModifiedOn] [datetime2] NULL,
[ModifiedBy] [nvarchar] (50) NULL,
[DispatchDay] [int] NULL,
[RFIDFlag] [bit] NULL,
[CriticalStageGate] [nvarchar] (10) NULL,
[SpatialConstraintJobIDs] [varchar] (255) NULL,
[Line] [varchar] (10) NULL,
[ConcurrentJobIDs] [varchar] (255) NULL,
[Shift] [int] NULL,
[description] [varchar] (255) NOT NULL CONSTRAINT [DF__BuildPlan__descr__668030F6] DEFAULT ('NA')
)
GO
ALTER TABLE [ref].[BuildPlanJobs] ADD CONSTRAINT [PK__BuildPla__056690E27CF2D7E0_OLD] PRIMARY KEY CLUSTERED ([JobID])
GO
